# Generated by Django 3.2.14 on 2022-09-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='whatever',
        ),
    ]
