# Generated by Django 3.2.14 on 2022-09-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_whatever'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custom_commissions',
            new_name='CustomCommissions',
        ),
    ]
