# Generated by Django 3.2.14 on 2022-09-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_custom_commissions_customcommissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reference_sheet_commission',
            new_name='ReferenceSheetCommission',
        ),
    ]
