# Generated by Django 3.2.14 on 2022-09-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_regular_commission_regularcommission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_art',
            new_name='AddArt',
        ),
    ]
